export const USER_ROLE_LIST="USER_ROLE_LIST";
export const USER_ROLE_LIST_DATA="USER_ROLE_LIST_DATA";
export const ROLE_USER_ASSIGN="ROLE_USER_ASSIGN";
export const ROLE_USER_ASSIGN_FRESH = "ROLE_USER_ASSIGN_FRESH";
export const MODULE_EDIT_FRESH = "MODULE_EDIT_FRESH";
export const MODULE_DELETE_FRESH = "MODULE_DELETE_FRESH";
export const MODULE_LIST_FRESH = "MODULE_LIST_FRESH";