export const EDIT_PROFILE = "EDIT_PROFILE"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const EDIT_PASSWORD = "EDIT_PASSWORD"
export const RESET_PROFILE_FLAG = "RESET_PROFILE_FLAG";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const ADD_NOTIFICATION_FRESH = "ADD_NOTIFICATION_FRESH"
export const NOTIFICATION_DATA = "NOTIFICATION_DATA"
